[package]

name = "stack"
version = "0.0.1"

[dependencies]
clap = "2.29.2"
env_logger = "0.5.3"
error-chain = "0.11.0"
futures = "0.1.18"
git2 = "0.6.11"
hubcaps = "0.4.3"
log = "0.4.0"
regex = "0.2.5"
tokio-core = "0.1.12"
